-- TRIGGER PARA CADASTRAR A FACCAO NA NACAO DO LIDER QUANDO CRIADA
CREATE OR REPLACE TRIGGER lider_faccao_nacao
AFTER INSERT ON FACCAO
FOR EACH ROW
DECLARE
    v_lider lider%ROWTYPE;
BEGIN
    SELECT * INTO v_lider FROM LIDER WHERE CPI = :new.lider;
    INSERT INTO NACAO_faccao VALUES (v_lider.nacao, :new.nome);
END lider_faccao_nacao;


-- TRIGGER PARA CONFERIR SE O LIDER FOI ATUALIZADO NA ATUALIZACAO DE FACCAO
CREATE OR REPLACE TRIGGER update_lider_faccao_nacao
AFTER UPDATE ON FACCAO
FOR EACH ROW
DECLARE 
    v_lider lider%ROWTYPE;
BEGIN
    IF :old.lider <> :new.lider THEN
        SELECT * INTO v_lider FROM LIDER WHERE CPI = :new.lider;
        INSERT INTO NACAO_FACCAO VALUES (v_lider.nacao, :new.nome);
    END IF;
    
EXCEPTION 
    WHEN DUP_VAL_ON_INDEX THEN
    NULL; -- NAO E NECESSARIO FAZER NADA, FACCAO JA CADASTRADA
END;