-- TRIGGER PARA MANTER A QUANTIDADE DE NACOES ATUALIZADA NA TABELA FACCAO
CREATE OR REPLACE TRIGGER NRO_NACOES
AFTER INSERT OR DELETE ON NACAO_FACCAO -- A tabela FACCAO deve ser atualizada sempre que haver uma inserção ou remoção em NACAO_FACCAO
FOR EACH ROW

DECLARE
    V_QTD_NACOES NUMBER;

BEGIN
    IF INSERTING THEN
        SELECT QTD_NACOES INTO V_QTD_NACOES FROM FACCAO F WHERE F.NOME = :NEW.FACCAO;
        IF V_QTD_NACOES IS NULL THEN
            V_QTD_NACOES := 1;
        ELSE
            V_QTD_NACOES := V_QTD_NACOES + 1;
        END IF;
        
        UPDATE FACCAO SET QTD_NACOES = V_QTD_NACOES WHERE NOME = :NEW.FACCAO;
    
    ELSIF DELETING THEN
        SELECT QTD_NACOES INTO V_QTD_NACOES FROM FACCAO F WHERE F.NOME = :OLD.FACCAO;

        IF V_QTD_NACOES = 1 THEN
            V_QTD_NACOES := NULL;
        ELSE
            V_QTD_NACOES := V_QTD_NACOES - 1;
        END IF;
        
        UPDATE FACCAO SET QTD_NACOES = V_QTD_NACOES WHERE NOME = :OLD.FACCAO;
        
    END IF;

EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Erro desconhecido');

END;